Repository boostcampwm-2024/refactor-web39-OctoDocs, pull requests merged in 2025-02, with the labels that each got.

#70 AI 질문 기능 구현
  apps/frontend/src/app/App.tsx
  apps/frontend/src/features/AI/api/langchainApi.ts
  apps/frontend/src/features/AI/index.tsx
  apps/frontend/src/features/AI/model/langchainTypes.ts
  apps/frontend/src/features/AI/model/useLangchain.ts
  apps/frontend/src/features/AI/ui/AIButton/index.tsx
  apps/frontend/src/features/AI/ui/AIPanel/index.tsx
  apps/frontend/src/features/AI/ui/QuestionForm/index.tsx
  apps/frontend/src/widgets/AIToolView/index.tsx
  apps/frontend/src/widgets/AIToolView/ui/index.tsx
Labels: 🐰🐣 FE, ✨ Feature

#71 V1.2.0 배포
  README.md
  apps/backend/package.json
  apps/backend/src/app.module.ts
  apps/backend/src/langchain/dtos/queryRequest.dto.ts
  apps/backend/src/langchain/langchain.controller.spec.ts
  apps/backend/src/langchain/langchain.controller.ts
  apps/backend/src/langchain/langchain.module.ts
  apps/backend/src/langchain/langchain.service.spec.ts
  apps/backend/src/langchain/langchain.service.ts
  apps/backend/src/tasks/tasks.module.ts
  apps/backend/src/tasks/tasks.service.ts
  apps/frontend/src/app/App.tsx
  apps/frontend/src/features/AI/api/langchainApi.ts
  apps/frontend/src/features/AI/index.tsx
  apps/frontend/src/features/AI/model/langchainTypes.ts
  apps/frontend/src/features/AI/model/useLangchain.ts
  apps/frontend/src/features/AI/ui/AIButton/index.tsx
  apps/frontend/src/features/AI/ui/AIPanel/index.tsx
  apps/frontend/src/features/AI/ui/QuestionForm/index.tsx
  apps/frontend/src/widgets/AIToolView/index.tsx
  apps/frontend/src/widgets/AIToolView/ui/index.tsx
  apps/websocket/src/yjs/yjs.schema.ts
  compose.local.yml
  yarn.lock
Labels: 🌍 new release

#81 fix: postgres vector extension 활성화
  apps/backend/src/page/page.repository.ts
Labels: 🐛 Bug, 🐧🚀😶‍🌫️ BE

#88 Refactor be #37
  apps/backend/nest-cli.json
  apps/backend/package.json
  apps/backend/src/tasks/tasks.module.ts
  apps/backend/src/tasks/tasks.service.ts
  apps/backend/tsconfig.json
  apps/websocket/nest-cli.json
  apps/websocket/src/redis/redis.module.ts
  apps/websocket/src/redis/redis.service.ts
  apps/websocket/src/yjs/yjs.module.ts
  apps/websocket/src/yjs/yjs.service.ts
  apps/websocket/tsconfig.json
  libs/redis/src/index.ts
  libs/redis/src/redis.module.ts
  libs/redis/src/redis.service.spec.ts
  libs/redis/src/redis.service.ts
  libs/redis/tsconfig.lib.json
  nest-cli.json
  package.json
  services/backend/Dockerfile.local
  services/backend/Dockerfile.prod
  services/module/Dockerfile
  services/module/Dockerfile.init
  services/websocket/Dockerfile.local
  services/websocket/Dockerfile.prod
  tsconfig.json
  yarn.lock
Labels: 🐧🚀😶‍🌫️ BE, ♻️ Refactor

#91 RAG 질문 history 구현
  apps/frontend/src/features/AI/model/useLangchainStore.ts
  apps/frontend/src/features/AI/model/useQnA.ts
  apps/frontend/src/features/AI/ui/AIPanel/index.tsx
  apps/frontend/src/features/AI/ui/QnA/index.tsx
  apps/frontend/src/features/AI/ui/QuestionForm/index.tsx
Labels: 🐰🐣 FE, ✨ Feature

#93 키워드 기반 검색 및 hybrid 검색 성능 개선
  apps/backend/src/langchain/langchain.service.ts
  apps/backend/src/page/page.controller.spec.ts
  apps/scheduler/src/langchain/langchain.service.ts
  apps/scheduler/src/tasks/tasks.service.ts
  compose.local.yml
  libs/page/src/page.entity.ts
  libs/page/src/page.repository.ts
  services/postgres/Dockerfile
  services/postgres/init.sql
Labels: 🐧🚀😶‍🌫️ BE, ♻️ Refactor

#95 응답 생성 중단 기능 구현
  apps/frontend/src/features/AI/model/useLangchain.ts
  apps/frontend/src/features/AI/model/useLangchainStore.ts
  apps/frontend/src/features/AI/model/useQnA.ts
  apps/frontend/src/features/AI/ui/AIPanel/index.tsx
  apps/frontend/src/features/AI/ui/QuestionForm/index.tsx
Labels: 🐰🐣 FE, ✨ Feature

#97 LLM 응답 중단 기능 개발
  apps/backend/src/abort/chat-abort.controller.spec.ts
  apps/backend/src/abort/chat-abort.controller.ts
  apps/backend/src/abort/chat-abort.module.ts
  apps/backend/src/abort/chat-abort.service.spec.ts
  apps/backend/src/abort/chat-abort.service.ts
  apps/backend/src/abort/dtos/AbortFailResponseDto.ts
  apps/backend/src/abort/dtos/AbortSuccessResponseDto.ts
  apps/backend/src/app.module.ts
  apps/backend/src/langchain/langchain.controller.spec.ts
  apps/backend/src/langchain/langchain.controller.ts
  apps/backend/src/langchain/langchain.module.ts
  apps/backend/src/langchain/langchain.service.ts
  services/nginx/conf.d/default.conf
  services/nginx/conf.d/prod_nginx.conf
  services/postgres/Dockerfile
Labels: 🐧🚀😶‍🌫️ BE, ✨ Feature, ♻️ Refactor
