Repository boostcampwm-2024/refactor-web39-OctoDocs, pull requests merged in 2025-01, with the labels that each got.

#10 Refactor be #4
  apps/backend/src/redis/redis.service.ts
  apps/backend/src/tasks/tasks.service.ts
  apps/websocket/src/redis/redis.service.ts
  apps/websocket/src/yjs/yjs.service.ts
Labels: bug

#32 hotfix: lint 오류 수정
  apps/backend/.eslintrc.js
  apps/backend/src/page/page.service.ts
  apps/backend/src/tasks/tasks.service.ts
  apps/frontend/eslint.config.js
  apps/websocket/.eslintrc.js
  package.json
Labels: 🐛 Bug

#41 redis 분산 락 제거 후 watch를 사용한 낙관적 락으로 변경
  apps/backend/src/redis/redis.service.ts
  apps/backend/src/tasks/tasks.service.ts
Labels: 🐧🚀😶‍🌫️ BE, ♻️ Refactor

#43 로그인 여부 체크 api 구현
  apps/backend/src/auth/auth.controller.ts
  apps/backend/src/auth/dtos/loginResponse.dto.ts
  apps/backend/src/auth/guards/jwt-auth.guard.ts
Labels: 🐧🚀😶‍🌫️ BE, ♻️ Refactor

#46 docker .env bind mount 제거
  .github/workflows/auto-assign-merge.yml
  apps/backend/src/auth/auth.controller.spec.ts
  compose.local.yml
  compose.prod.yml
Labels: 🐧🚀😶‍🌫️ BE, ♻️ Refactor

#50 Refactor : 워크스페이스 리스트 버튼 클릭 렌더링 개선
  apps/frontend/package.json
  apps/frontend/src/app/providers/TanstackQueryProvider.tsx
  apps/frontend/src/features/auth/api/authApi.ts
  apps/frontend/src/features/auth/index.ts
  apps/frontend/src/features/auth/model/authQueries.ts
  apps/frontend/src/features/pageSidebar/ui/WorkspaceNav/index.tsx
  apps/frontend/src/features/workspace/model/workspaceQuries.ts
  apps/frontend/src/shared/ui/Divider/index.tsx
  apps/frontend/src/widgets/UserInfoView/ui/index.tsx
  yarn.lock
Labels: 🐰🐣 FE, ♻️ Refactor

#53 refactor: page 조회 기능 query builder로 수정
  apps/backend/src/app.module.ts
  apps/backend/src/page/page.entity.ts
  apps/backend/src/page/page.service.spec.ts
  apps/backend/src/page/page.service.ts
Labels: 🐧🚀😶‍🌫️ BE, ♻️ Refactor

#51 엣지 생성, 삭제 api로 작업 위임
  apps/backend/src/edge/edge.controller.spec.ts
  apps/backend/src/edge/edge.controller.ts
  apps/backend/src/edge/edge.service.spec.ts
  apps/backend/src/edge/edge.service.ts
  apps/backend/src/redis/redis.service.ts
  apps/backend/src/tasks/tasks.service.ts
  apps/websocket/src/yjs/yjs.service.ts
  yarn.lock
Labels: 🐛 Bug, 🐧🚀😶‍🌫️ BE

#55 에러 해결, 필요없는 코드 정리
  .github/workflows/ci-pipeline.yml
  apps/backend/src/edge/edge.service.ts
  apps/backend/src/node/dtos/coordinateResponse.dto.ts
  apps/backend/src/node/dtos/createNode.dto.ts
  apps/backend/src/node/dtos/findNodeResponse.dto.ts
  apps/backend/src/node/dtos/messageResponse.dto.ts
  apps/backend/src/node/dtos/moveNode.dto.ts
  apps/backend/src/node/dtos/updateNode.dto.ts
  apps/backend/src/node/node.controller.spec.ts
  apps/backend/src/node/node.controller.ts
  apps/backend/src/node/node.service.spec.ts
  apps/backend/src/node/node.service.ts
  apps/backend/src/page/dtos/findPagesResponse.dto.ts
  apps/backend/src/page/dtos/updatePage.dto.ts
  apps/backend/src/page/dtos/updatePartialPage.dto.ts
  apps/backend/src/page/page.controller.spec.ts
  apps/backend/src/page/page.controller.ts
  apps/backend/src/page/page.repository.ts
  apps/backend/src/page/page.service.spec.ts
  apps/backend/src/page/page.service.ts
  apps/backend/test/package.json
  apps/frontend/vite.config.ts
  compose.local.yml
  package.json
  yarn.lock
Labels: 🐛 Bug, 🐧🚀😶‍🌫️ BE, ♻️ Refactor
